### ISSUE TITLE
Plugin does not load on Minecraft 1.18.2.

### ISSUE THREAD

**Issue by RealTriassic** [oscailte-mc/AutoBroadcast#5]
### Error

```
[07:21:07 INFO]: [AutoBroadcast] Comments were partially lost whilst updating the config.
You can grab the v2.0.1 default configuration from the resource page.
[07:21:08 ERROR]: Error occurred while enabling AutoBroadcast v2.0.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
        at io.paradaux.autobroadcast.adventure.AdventureImpl.<init>(AdventureImpl.java:67) ~[AutoBroadcast-2.0.1.jar:?]
        at io.paradaux.autobroadcast.AutoBroadcast.onEnable(AutoBroadcast.java:75) ~[AutoBroadcast-2.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:21:08 INFO]: [AutoBroadcast] Disabling AutoBroadcast v2.0.1
```

### Information
Server Software: Purpur 1.18.2 (Build 1574)
Java version: Java 17

**Comment by ParadauxIO** [comment]
Thanks for letting me know, will take a look and have a patch out soon

**Comment by ParadauxIO** [comment]
Problem caused by the recent minimessage merge https://github.com/KyoriPowered/adventure/issues/402 which has interferred with the version shaded by the plugin. Will have a release out in a few minutes.

**Comment by ParadauxIO** [comment]
Resolved in https://github.com/oscailte-mc/AutoBroadcast/releases/tag/2.0.2
